server:
  port: 8088
spring:
  application:
    name: cloud-server-cart
  redis:
    host: wxw.plus
eureka:
  client:
    service-url:
      defaultZone: http://bs.wxw.com:10086/eureka
    registry-fetch-interval-seconds: 30
  instance:
    #避免显示主机名
    instance-id: cloud-server-cart
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90
wxw:
  jwt:
    pubKeyPath: F:\Study_GO\BS2020\rsa\rsa.pub # 公钥地址
    cookieName: BS_TOKEN