server:
  port: 10010
spring:
  application:
    name: cloud-gateway-server
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: cloud-bs-service #路由的ID，没有固定规则但要求唯一，建议配合服务名
          uri: lb://cloud-bs-service   #开启动态路由
          predicates:
            - Path=/api/item/**   #断言, 路由到商品的微服务
          filters:
            - StripPrefix=2
        - id: cloud-server-fileload
          uri: lb://cloud-server-fileload
          predicates:
            - Path=/api/load/**
          filters:
            - StripPrefix=2
        - id: cloud-bs-search
          uri: lb://cloud-bs-search
          predicates:
            - Path=/api/search/**   # 路由到搜索微服务
          filters:
            - StripPrefix=2
        - id: cloud-user-service
          uri: lb://cloud-user-service
          predicates:
            - Path=/api/user/**   # 路由到用户中心
          filters:
            - StripPrefix=2

eureka:
  client:
    fetch-registry: true  #需要拉取服务
    register-with-eureka: true    #需要在eureka中注册自己
    service-url:
     defaultZone: http://bs.wxw.com:10086/eureka
  instance:
    #避免显示主机名
    instance-id: cloud-gateway-server
    #显示IP地址
    prefer-ip-address: true
    #Eureka客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
    lease-renewal-interval-in-seconds: 30
    #Eureka服务端在收到最后一次心跳后等待时间上线，单位为秒（默认为90秒），超时将剔除服务
    lease-expiration-duration-in-seconds: 90
